<?php

/**
 * @file
 * Queue Watcher module file.
 */

/**
 * Implements hook_cron(). 
 */
function queue_watcher_cron() {
  $config = \Drupal::config('queue_watcher.config');

  $to_watch = [];
  foreach ($config->get('watch_queues') as $watch_item) {
    if (!empty($watch_item['queue_name'])) {
      $name = $watch_item['queue_name'];
    }
  }

  $recipients = [];
  foreach (explode(', ', $config->get('mail_recipients')) as $address) {
    $recipients[$address] = $address;
  }
  if ($config->get('use_site_mail')) {
    $site = \Drupal::config('system.site');
    if ($address = $site->get('mail')) {
      $recipients[$address] = $address;
    }
  }
  if ($config->get('use_admin_mail')) {
    $account = \Drupal::entityTypeManager()->getStorage('user')->load(1);
    if ($account && ($address = $account->getEmail())) {
      $recipients[$address] = $address;
    }
  }

  if (!empty($recipients)) {
    // Send the reports to the given mail addresses.
  }
}
